/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as CollaborationsRouteImport } from './routes/collaborations'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FundingRouteImport } from './routes/funding'
import { Route as InnovationScoreRouteImport } from './routes/innovation-score'
import { Route as LabResourcesRouteImport } from './routes/lab-resources'
import { Route as PatentsRouteImport } from './routes/patents'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaborationsRoute = CollaborationsRouteImport.update({
  id: '/collaborations',
  path: '/collaborations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FundingRoute = FundingRouteImport.update({
  id: '/funding',
  path: '/funding',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovationScoreRoute = InnovationScoreRouteImport.update({
  id: '/innovation-score',
  path: '/innovation-score',
  getParentRoute: () => rootRouteImport,
} as any)
const LabResourcesRoute = LabResourcesRouteImport.update({
  id: '/lab-resources',
  path: '/lab-resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PatentsRoute = PatentsRouteImport.update({
  id: '/patents',
  path: '/patents',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/collaborations': typeof CollaborationsRoute
  '/dashboard': typeof DashboardRoute
  '/funding': typeof FundingRoute
  '/innovation-score': typeof InnovationScoreRoute
  '/lab-resources': typeof LabResourcesRoute
  '/patents': typeof PatentsRoute
  '/profile': typeof ProfileRoute
  '/publications': typeof PublicationsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/collaborations': typeof CollaborationsRoute
  '/dashboard': typeof DashboardRoute
  '/funding': typeof FundingRoute
  '/innovation-score': typeof InnovationScoreRoute
  '/lab-resources': typeof LabResourcesRoute
  '/patents': typeof PatentsRoute
  '/profile': typeof ProfileRoute
  '/publications': typeof PublicationsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/collaborations': typeof CollaborationsRoute
  '/dashboard': typeof DashboardRoute
  '/funding': typeof FundingRoute
  '/innovation-score': typeof InnovationScoreRoute
  '/lab-resources': typeof LabResourcesRoute
  '/patents': typeof PatentsRoute
  '/profile': typeof ProfileRoute
  '/publications': typeof PublicationsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/collaborations'
    | '/dashboard'
    | '/funding'
    | '/innovation-score'
    | '/lab-resources'
    | '/patents'
    | '/profile'
    | '/publications'
    | '/reports'
    | '/settings'
    | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/collaborations'
    | '/dashboard'
    | '/funding'
    | '/innovation-score'
    | '/lab-resources'
    | '/patents'
    | '/profile'
    | '/publications'
    | '/reports'
    | '/settings'
    | '/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/collaborations'
    | '/dashboard'
    | '/funding'
    | '/innovation-score'
    | '/lab-resources'
    | '/patents'
    | '/profile'
    | '/publications'
    | '/reports'
    | '/settings'
    | '/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  CollaborationsRoute: typeof CollaborationsRoute
  DashboardRoute: typeof DashboardRoute
  FundingRoute: typeof FundingRoute
  InnovationScoreRoute: typeof InnovationScoreRoute
  LabResourcesRoute: typeof LabResourcesRoute
  PatentsRoute: typeof PatentsRoute
  ProfileRoute: typeof ProfileRoute
  PublicationsRoute: typeof PublicationsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaborations': {
      id: '/collaborations'
      path: '/collaborations'
      fullPath: '/collaborations'
      preLoaderRoute: typeof CollaborationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funding': {
      id: '/funding'
      path: '/funding'
      fullPath: '/funding'
      preLoaderRoute: typeof FundingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovation-score': {
      id: '/innovation-score'
      path: '/innovation-score'
      fullPath: '/innovation-score'
      preLoaderRoute: typeof InnovationScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab-resources': {
      id: '/lab-resources'
      path: '/lab-resources'
      fullPath: '/lab-resources'
      preLoaderRoute: typeof LabResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patents': {
      id: '/patents'
      path: '/patents'
      fullPath: '/patents'
      preLoaderRoute: typeof PatentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  CollaborationsRoute: CollaborationsRoute,
  DashboardRoute: DashboardRoute,
  FundingRoute: FundingRoute,
  InnovationScoreRoute: InnovationScoreRoute,
  LabResourcesRoute: LabResourcesRoute,
  PatentsRoute: PatentsRoute,
  ProfileRoute: ProfileRoute,
  PublicationsRoute: PublicationsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
