import React, { useState } from 'react'
import { FileText, Download, FileSpreadsheet, ExternalLink } from 'lucide-react'
import AppLayout from '../components/layout/AppLayout'
import { reports } from '../services/mockData'

const typeColors = { PDF: { bg: 'rgba(6,182,212,0.12)', color: 'var(--accent-cyan-light)' }, DOCX: { bg: 'rgba(139,92,246,0.12)', color: 'var(--accent-violet)' } }

function Reports() {
  const [downloaded, setDownloaded] = useState({})

  const handleDownload = (r) => {
    const blob = new Blob([`INFERA REPORT\n\n${r.title}\nDate: ${r.date}\n\n${r.snippet}\n\nGenerated by Infera — Research Funding & Innovation Platform`], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url; a.download = `${r.title.replace(/[^a-z0-9]/gi, '_')}.txt`; a.click()
    URL.revokeObjectURL(url)
    setDownloaded((prev) => ({ ...prev, [r.id]: true }))
  }

  const generateBrief = () => {
    const blob = new Blob([
      'INFERA — MONTHLY INNOVATION BRIEF\n\n',
      'Research Portfolio Overview\n',
      '• 5 active grants tracked\n',
      '• 5 publications (2,130 total citations)\n',
      '• 5 patents (3 granted, 2 under examination)\n\n',
      'Funding Pipeline\n',
      '• 17 new opportunities identified\n',
      '• Top match: 94% fit — Advanced Materials for Next-Gen Water Purification\n\n',
      'Generated automatically by Infera — Research Funding & Innovation Platform'
    ], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url; a.download = 'infera_innovation_brief.txt'; a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <AppLayout
      title="Reports & Exports"
      subtitle="Download portfolio reports, landscape analyses, and custom innovation briefs."
    >
      <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem', maxWidth: '1200px', width: '100%', margin: '0 auto' }}>

        <section style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(290px, 1fr))', gap: '1.5rem' }}>
          {reports.map((r) => {
            const tc = typeColors[r.type] || typeColors.PDF
            return (
              <div key={r.id} className="glass-card" style={{ padding: '1.5rem', display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
                <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: '0.75rem' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '0.65rem' }}>
                    <div style={{ width: '36px', height: '36px', borderRadius: '10px', background: tc.bg, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                      <FileText size={18} color={tc.color} />
                    </div>
                    <div>
                      <h4 style={{ margin: 0, fontSize: '0.9rem', fontWeight: 700, color: 'var(--text-primary)', lineHeight: 1.3 }}>{r.title}</h4>
                    </div>
                  </div>
                  <span style={{ fontSize: '0.65rem', fontWeight: 700, padding: '0.2rem 0.55rem', borderRadius: '9999px', background: tc.bg, color: tc.color, whiteSpace: 'nowrap' }}>{r.type}</span>
                </div>
                <p style={{ margin: 0, fontSize: '0.82rem', color: 'var(--text-secondary)', lineHeight: 1.45 }}>{r.snippet}</p>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginTop: 'auto', paddingTop: '0.75rem', borderTop: '1px solid var(--border-color)' }}>
                  <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>{r.date} · {r.size}</span>
                  <button
                    onClick={() => handleDownload(r)}
                    className={downloaded[r.id] ? 'btn-secondary' : 'btn-ai-primary'}
                    style={{ marginLeft: 'auto', padding: '0.4rem 0.85rem', fontSize: '0.78rem', borderRadius: '8px', display: 'flex', alignItems: 'center', gap: '0.4rem' }}
                  >
                    <Download size={14} /> {downloaded[r.id] ? 'Downloaded' : 'Download'}
                  </button>
                </div>
              </div>
            )
          })}
        </section>

        <section className="glass-card" style={{ padding: '1.5rem', display: 'flex', alignItems: 'center', gap: '1.25rem', background: 'linear-gradient(145deg, rgba(139,92,246,0.08) 0%, rgba(6,182,212,0.08) 100%)' }}>
          <div style={{ width: '44px', height: '44px', borderRadius: '10px', background: 'rgba(139,92,246,0.15)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
            <FileSpreadsheet size={22} color="var(--accent-violet)" />
          </div>
          <div style={{ flexGrow: 1 }}>
            <h4 style={{ margin: 0, fontSize: '1rem', fontWeight: 700, color: 'var(--text-primary)' }}>Export Center</h4>
            <p style={{ margin: '0.25rem 0 0 0', fontSize: '0.82rem', color: 'var(--text-secondary)' }}>Generate a custom innovation brief summarizing your entire portfolio.</p>
          </div>
          <button onClick={generateBrief} className="btn-ai-secondary" style={{ padding: '0.55rem 1.1rem', fontSize: '0.82rem', borderRadius: '10px', display: 'flex', alignItems: 'center', gap: '0.4rem', flexShrink: 0 }}>
            <ExternalLink size={15} /> Generate Brief
          </button>
        </section>
      </div>
    </AppLayout>
  )
}

export default Reports