-- backend/database/seed_funding_data.sql
-- Synthetic seed script for 30 normalized funding opportunities
USE research_platform;

INSERT INTO funding_opportunities (id, title, funder, amount_range, deadline, semantic_fit, match_badges, description, research_domains, technology_areas, keywords, eligibility, research_stage, geographic_scope, funding_type, status)
VALUES (1, 'Quantum Computing & Information Science Grant Initiative', 'National Science Foundation (NSF)', '$150,000 - $500,000', '2026-12-01', 96, 'Topic match,Methodology match,PI overlap', 'Supports basic research in quantum algorithms, physical qubit scalability, entanglement metrics, and fault-tolerant quantum error correction architectures.', 'Quantum Computing, Computation Theory', 'Quantum Information Science, Superconducting Qubits, Vector Search', 'Quantum Computing, Qubits, Quantum Algorithms, Entanglement, Qubit Control', 'Ph.D. degree required, Academic or Industry Research Labs', 'Basic Research', 'Global', 'Research Grant', 'active')
ON DUPLICATE KEY UPDATE
title=VALUES(title), funder=VALUES(funder), amount_range=VALUES(amount_range), deadline=VALUES(deadline), semantic_fit=VALUES(semantic_fit), match_badges=VALUES(match_badges), description=VALUES(description), research_domains=VALUES(research_domains), technology_areas=VALUES(technology_areas), keywords=VALUES(keywords), eligibility=VALUES(eligibility), research_stage=VALUES(research_stage), geographic_scope=VALUES(geographic_scope), funding_type=VALUES(funding_type), status=VALUES(status);

INSERT INTO funding_opportunities (id, title, funder, amount_range, deadline, semantic_fit, match_badges, description, research_domains, technology_areas, keywords, eligibility, research_stage, geographic_scope, funding_type, status)
VALUES (2, 'Decarbonization Technologies & Clean Energy Innovation', 'U.S. Department of Energy (DOE)', '$500,000 - $1,200,000', '2026-10-15', 88, 'Methodology match,Equipment overlap', 'Research initiative focused on industrial decarbonization, renewable grid integration, green hydrogen production, and direct air carbon capture.', 'Energy & Sustainability, Environmental Science', 'Decarbonization, Clean Energy, Carbon Capture, Smart Grid', 'Decarbonization, Clean Energy, Solar, Wind, Carbon Storage, Renewable Energy', 'University, National Lab, or Non-profit Organization', 'Applied Research', 'United States', 'Research Grant', 'active')
ON DUPLICATE KEY UPDATE
title=VALUES(title), funder=VALUES(funder), amount_range=VALUES(amount_range), deadline=VALUES(deadline), semantic_fit=VALUES(semantic_fit), match_badges=VALUES(match_badges), description=VALUES(description), research_domains=VALUES(research_domains), technology_areas=VALUES(technology_areas), keywords=VALUES(keywords), eligibility=VALUES(eligibility), research_stage=VALUES(research_stage), geographic_scope=VALUES(geographic_scope), funding_type=VALUES(funding_type), status=VALUES(status);

INSERT INTO funding_opportunities (id, title, funder, amount_range, deadline, semantic_fit, match_badges, description, research_domains, technology_areas, keywords, eligibility, research_stage, geographic_scope, funding_type, status)
VALUES (3, 'AI in Translational Medicine & Deep Pathology Diagnostics', 'National Institutes of Health (NIH)', '$250,000 - $600,000', '2026-11-30', 94, 'Topic match,Co-author match', 'Grant focusing on applying deep learning architectures to clinical genomics, digital pathology image segmentation, and early stage disease biomarker prediction.', 'Healthcare AI, Bioinformatics, Medicine', 'Artificial Intelligence, Deep Learning, Pathology Diagnostics, Computer Vision', 'Healthcare AI, Deep Learning, Medical Diagnostics, Pathology, Bioinformatics, Medical Imaging', 'Tenure-track or Clinical Faculty', 'Translational Research', 'Global', 'Research Grant', 'active')
ON DUPLICATE KEY UPDATE
title=VALUES(title), funder=VALUES(funder), amount_range=VALUES(amount_range), deadline=VALUES(deadline), semantic_fit=VALUES(semantic_fit), match_badges=VALUES(match_badges), description=VALUES(description), research_domains=VALUES(research_domains), technology_areas=VALUES(technology_areas), keywords=VALUES(keywords), eligibility=VALUES(eligibility), research_stage=VALUES(research_stage), geographic_scope=VALUES(geographic_scope), funding_type=VALUES(funding_type), status=VALUES(status);

INSERT INTO funding_opportunities (id, title, funder, amount_range, deadline, semantic_fit, match_badges, description, research_domains, technology_areas, keywords, eligibility, research_stage, geographic_scope, funding_type, status)
VALUES (4, 'Advanced Materials Research & Nanotechnology Grants', 'Defense Advanced Research Projects Agency (DARPA)', '$300,000 - $800,000', '2026-09-20', 75, 'Topic match', 'Program supporting novel synthetic materials synthesis, high-temperature superconductors, self-healing polymers, and nanostructure fabrication.', 'Materials Science, Nanotechnology', 'Advanced Nanomaterials, Metamaterials, Nanofabrication', 'Nanotechnology, Materials Science, Metamaterials, Nanofabrication, Polymers', 'Approved US academic research teams and defense laboratories', 'Applied Research', 'United States', 'Contract', 'active')
ON DUPLICATE KEY UPDATE
title=VALUES(title), funder=VALUES(funder), amount_range=VALUES(amount_range), deadline=VALUES(deadline), semantic_fit=VALUES(semantic_fit), match_badges=VALUES(match_badges), description=VALUES(description), research_domains=VALUES(research_domains), technology_areas=VALUES(technology_areas), keywords=VALUES(keywords), eligibility=VALUES(eligibility), research_stage=VALUES(research_stage), geographic_scope=VALUES(geographic_scope), funding_type=VALUES(funding_type), status=VALUES(status);

INSERT INTO funding_opportunities (id, title, funder, amount_range, deadline, semantic_fit, match_badges, description, research_domains, technology_areas, keywords, eligibility, research_stage, geographic_scope, funding_type, status)
VALUES (5, 'AI Research Grant 2026', 'National Science Foundation (NSF)', '$50,000 - $100,000', '2026-12-31', 95, 'AI,ML,RAG', 'Flagship grant program supporting foundational advances in generative AI, Retrieval Augmented Generation (RAG), Large Language Models (LLMs), and semantic memory systems.', 'Artificial Intelligence, Data Science, Machine Learning', 'RAG, LLMs, NLP, Transformers, Generative AI, Vector Search', 'AI, Machine Learning, RAG, LLMs, NLP, Generative AI, Deep Learning, Vector Search', 'Faculty researchers and academic research teams', 'Basic Research', 'Global', 'Research Grant', 'active')
ON DUPLICATE KEY UPDATE
title=VALUES(title), funder=VALUES(funder), amount_range=VALUES(amount_range), deadline=VALUES(deadline), semantic_fit=VALUES(semantic_fit), match_badges=VALUES(match_badges), description=VALUES(description), research_domains=VALUES(research_domains), technology_areas=VALUES(technology_areas), keywords=VALUES(keywords), eligibility=VALUES(eligibility), research_stage=VALUES(research_stage), geographic_scope=VALUES(geographic_scope), funding_type=VALUES(funding_type), status=VALUES(status);

INSERT INTO funding_opportunities (id, title, funder, amount_range, deadline, semantic_fit, match_badges, description, research_domains, technology_areas, keywords, eligibility, research_stage, geographic_scope, funding_type, status)
VALUES (6, 'Healthcare Innovation Fund', 'World Health Organization (WHO)', '$100,000 - $500,000', '2026-11-30', 88, 'Healthcare', 'Global WHO innovation fund for scalable digital healthcare interventions, remote patient monitoring devices, and community epidemiology tracking software.', 'Healthcare AI, Data Science, Public Health', 'Digital Health, Telemedicine, Health Informatics, Wearable Sensors', 'Healthcare, Health Informatics, Digital Health, Biomedical Systems, Telemedicine', 'Healthcare Institutions & Accredited Research Foundations', 'Applied Research', 'Global', 'Innovation Grant', 'active')
ON DUPLICATE KEY UPDATE
title=VALUES(title), funder=VALUES(funder), amount_range=VALUES(amount_range), deadline=VALUES(deadline), semantic_fit=VALUES(semantic_fit), match_badges=VALUES(match_badges), description=VALUES(description), research_domains=VALUES(research_domains), technology_areas=VALUES(technology_areas), keywords=VALUES(keywords), eligibility=VALUES(eligibility), research_stage=VALUES(research_stage), geographic_scope=VALUES(geographic_scope), funding_type=VALUES(funding_type), status=VALUES(status);

INSERT INTO funding_opportunities (id, title, funder, amount_range, deadline, semantic_fit, match_badges, description, research_domains, technology_areas, keywords, eligibility, research_stage, geographic_scope, funding_type, status)
VALUES (7, 'Smart Agriculture & Soil Precision Sensing Program', 'Food and Agriculture Organization (FAO)', '$25,000 - $75,000', '2026-10-15', 82, 'Agriculture', 'FAO smart agriculture grant aimed at climate-resilient crop management, precision Internet-of-Things sensor networks, and autonomous soil nitrate analysis.', 'Smart Agriculture, Environmental Science', 'Precision Agriculture, Smart Sensing, Soil Analytics, AgTech IoT', 'Agriculture, Precision Farming, Crop Yield, Soil Monitoring, AgTech, Sensors', 'Agricultural researchers and agricultural university departments', 'Applied Research', 'Global', 'Research Grant', 'active')
ON DUPLICATE KEY UPDATE
title=VALUES(title), funder=VALUES(funder), amount_range=VALUES(amount_range), deadline=VALUES(deadline), semantic_fit=VALUES(semantic_fit), match_badges=VALUES(match_badges), description=VALUES(description), research_domains=VALUES(research_domains), technology_areas=VALUES(technology_areas), keywords=VALUES(keywords), eligibility=VALUES(eligibility), research_stage=VALUES(research_stage), geographic_scope=VALUES(geographic_scope), funding_type=VALUES(funding_type), status=VALUES(status);

INSERT INTO funding_opportunities (id, title, funder, amount_range, deadline, semantic_fit, match_badges, description, research_domains, technology_areas, keywords, eligibility, research_stage, geographic_scope, funding_type, status)
VALUES (8, 'Cybersecurity & Zero-Trust Architecture Grant', 'National Institute of Standards and Technology (NIST)', '$75,000 - $150,000', '2026-09-20', 91, 'Cybersecurity', 'NIST research grant for resilient network cryptography, automated vulnerability scanning using static analysis, and zero-trust verification protocols.', 'Cybersecurity, Computer Networks', 'Network Cryptography, Zero Trust Systems, Threat Detection, Static Analysis', 'Cybersecurity, Cryptography, Zero Trust, Network Security, Encryption, Threat Detection', 'University researchers and cybersecurity labs', 'Applied Research', 'Global', 'Research Grant', 'active')
ON DUPLICATE KEY UPDATE
title=VALUES(title), funder=VALUES(funder), amount_range=VALUES(amount_range), deadline=VALUES(deadline), semantic_fit=VALUES(semantic_fit), match_badges=VALUES(match_badges), description=VALUES(description), research_domains=VALUES(research_domains), technology_areas=VALUES(technology_areas), keywords=VALUES(keywords), eligibility=VALUES(eligibility), research_stage=VALUES(research_stage), geographic_scope=VALUES(geographic_scope), funding_type=VALUES(funding_type), status=VALUES(status);

INSERT INTO funding_opportunities (id, title, funder, amount_range, deadline, semantic_fit, match_badges, description, research_domains, technology_areas, keywords, eligibility, research_stage, geographic_scope, funding_type, status)
VALUES (9, 'Robotics & Surgical Autonomous Systems Award', 'IEEE Robotics and Automation Society', '$50,000 - $200,000', '2026-09-15', 89, 'Robotics', 'IEEE grant supporting next-generation minimally invasive surgical robotics, haptic feedback actuators, and real-time visual simultaneous localization and mapping (SLAM).', 'Robotics, Computer Vision, Control Systems', 'Autonomous Mobile Robotics, Haptics, Computer Vision, SLAM', 'Robotics, Autonomous Systems, Mechatronics, Kinematics, SLAM, Haptics', 'IEEE Members and robotics laboratory researchers', 'Prototyping', 'Global', 'Award', 'active')
ON DUPLICATE KEY UPDATE
title=VALUES(title), funder=VALUES(funder), amount_range=VALUES(amount_range), deadline=VALUES(deadline), semantic_fit=VALUES(semantic_fit), match_badges=VALUES(match_badges), description=VALUES(description), research_domains=VALUES(research_domains), technology_areas=VALUES(technology_areas), keywords=VALUES(keywords), eligibility=VALUES(eligibility), research_stage=VALUES(research_stage), geographic_scope=VALUES(geographic_scope), funding_type=VALUES(funding_type), status=VALUES(status);

INSERT INTO funding_opportunities (id, title, funder, amount_range, deadline, semantic_fit, match_badges, description, research_domains, technology_areas, keywords, eligibility, research_stage, geographic_scope, funding_type, status)
VALUES (10, 'Quantum Software & Error Mitigation Fellowship', 'IBM Quantum Research', '$100,000 - $500,000', '2025-12-31', 94, 'Quantum', 'IBM fellowship program for novel quantum software development, noise cancellation techniques, and pulse-level superconducting qubit optimization.', 'Quantum Computing, Software Engineering', 'Qubit Control, Quantum Error Correction, Qiskit', 'Quantum, Qubit, Superconducting Qubits, Quantum Software, Noise Reduction', 'Early-career researchers and PhD candidates', 'Basic Research', 'Global', 'Fellowship', 'closed')
ON DUPLICATE KEY UPDATE
title=VALUES(title), funder=VALUES(funder), amount_range=VALUES(amount_range), deadline=VALUES(deadline), semantic_fit=VALUES(semantic_fit), match_badges=VALUES(match_badges), description=VALUES(description), research_domains=VALUES(research_domains), technology_areas=VALUES(technology_areas), keywords=VALUES(keywords), eligibility=VALUES(eligibility), research_stage=VALUES(research_stage), geographic_scope=VALUES(geographic_scope), funding_type=VALUES(funding_type), status=VALUES(status);

INSERT INTO funding_opportunities (id, title, funder, amount_range, deadline, semantic_fit, match_badges, description, research_domains, technology_areas, keywords, eligibility, research_stage, geographic_scope, funding_type, status)
VALUES (11, 'Natural Language Processing for Low-Resource Languages', 'Google Research Initiative', '$80,000 - $250,000', '2026-11-15', 93, 'NLP,AI', 'Research support for multilingual transformer models, low-resource speech synthesis, cross-lingual representation learning, and translation benchmarks.', 'Natural Language Processing, Artificial Intelligence', 'NLP, Transformers, Multilingual LLMs, Speech Processing', 'NLP, Language Models, Transformers, Low-Resource Languages, Speech Synthesis', 'Academic researchers and non-profit computational linguistics groups', 'Applied Research', 'Global', 'Research Grant', 'active')
ON DUPLICATE KEY UPDATE
title=VALUES(title), funder=VALUES(funder), amount_range=VALUES(amount_range), deadline=VALUES(deadline), semantic_fit=VALUES(semantic_fit), match_badges=VALUES(match_badges), description=VALUES(description), research_domains=VALUES(research_domains), technology_areas=VALUES(technology_areas), keywords=VALUES(keywords), eligibility=VALUES(eligibility), research_stage=VALUES(research_stage), geographic_scope=VALUES(geographic_scope), funding_type=VALUES(funding_type), status=VALUES(status);

INSERT INTO funding_opportunities (id, title, funder, amount_range, deadline, semantic_fit, match_badges, description, research_domains, technology_areas, keywords, eligibility, research_stage, geographic_scope, funding_type, status)
VALUES (12, 'Clean Energy Storage & Solid-State Battery Challenge', 'European Research Council (ERC)', '$400,000 - $1,000,000', '2026-12-15', 86, 'CleanEnergy', 'Breakthrough research challenge funding next-generation solid-state lithium battery electrolytes, grid-scale thermal storage, and electrochemical efficiency.', 'Energy & Sustainability, Chemistry', 'Solid-State Batteries, Energy Storage, Electrochemistry', 'Battery, Clean Energy, Energy Storage, Electrochemistry, Electrolytes', 'European Union and international associated research institutions', 'Experimental Development', 'European Union', 'Challenge Grant', 'active')
ON DUPLICATE KEY UPDATE
title=VALUES(title), funder=VALUES(funder), amount_range=VALUES(amount_range), deadline=VALUES(deadline), semantic_fit=VALUES(semantic_fit), match_badges=VALUES(match_badges), description=VALUES(description), research_domains=VALUES(research_domains), technology_areas=VALUES(technology_areas), keywords=VALUES(keywords), eligibility=VALUES(eligibility), research_stage=VALUES(research_stage), geographic_scope=VALUES(geographic_scope), funding_type=VALUES(funding_type), status=VALUES(status);

INSERT INTO funding_opportunities (id, title, funder, amount_range, deadline, semantic_fit, match_badges, description, research_domains, technology_areas, keywords, eligibility, research_stage, geographic_scope, funding_type, status)
VALUES (13, 'Climate Change Modeling & Satellite Earth Observation', 'NASA Earth Science Division', '$200,000 - $650,000', '2026-10-30', 87, 'Climate,DataScience', 'Geospatial data analysis using hyperspectral satellite images to model deforestation, ocean temperature anomalies, and global ice sheet retreat.', 'Environmental Science, Data Science', 'Remote Sensing, Geospatial Analytics, Climate Modeling, GIS', 'Climate Modeling, Remote Sensing, Geospatial, Satellite Imagery, GIS', 'Earth science researchers and university remote sensing units', 'Applied Research', 'Global', 'Research Grant', 'active')
ON DUPLICATE KEY UPDATE
title=VALUES(title), funder=VALUES(funder), amount_range=VALUES(amount_range), deadline=VALUES(deadline), semantic_fit=VALUES(semantic_fit), match_badges=VALUES(match_badges), description=VALUES(description), research_domains=VALUES(research_domains), technology_areas=VALUES(technology_areas), keywords=VALUES(keywords), eligibility=VALUES(eligibility), research_stage=VALUES(research_stage), geographic_scope=VALUES(geographic_scope), funding_type=VALUES(funding_type), status=VALUES(status);

INSERT INTO funding_opportunities (id, title, funder, amount_range, deadline, semantic_fit, match_badges, description, research_domains, technology_areas, keywords, eligibility, research_stage, geographic_scope, funding_type, status)
VALUES (14, 'Autonomous Drone Systems & Vision Navigation Grant', 'Air Force Office of Scientific Research (AFOSR)', '$150,000 - $450,000', '2026-09-10', 84, 'Robotics,Vision', 'Vision-based autonomous flight control for unmanned aerial vehicles operating in GPS-denied environments using edge computer vision algorithms.', 'Autonomous Systems, Computer Vision, Robotics', 'Computer Vision, Autonomous Flight, Edge Computing, Visual Odometry', 'Drones, Autonomous Navigation, Computer Vision, GPS-Denied, Edge Computing', 'Accredited aerospace engineering departments and research units', 'Applied Research', 'United States', 'Research Grant', 'active')
ON DUPLICATE KEY UPDATE
title=VALUES(title), funder=VALUES(funder), amount_range=VALUES(amount_range), deadline=VALUES(deadline), semantic_fit=VALUES(semantic_fit), match_badges=VALUES(match_badges), description=VALUES(description), research_domains=VALUES(research_domains), technology_areas=VALUES(technology_areas), keywords=VALUES(keywords), eligibility=VALUES(eligibility), research_stage=VALUES(research_stage), geographic_scope=VALUES(geographic_scope), funding_type=VALUES(funding_type), status=VALUES(status);

INSERT INTO funding_opportunities (id, title, funder, amount_range, deadline, semantic_fit, match_badges, description, research_domains, technology_areas, keywords, eligibility, research_stage, geographic_scope, funding_type, status)
VALUES (15, 'Edge Computing Security & Industrial IoT Vulnerability', 'Intel University Research Office', '$60,000 - $180,000', '2026-11-01', 85, 'Cybersecurity,IoT', 'Hardware-enforced trusted execution environments, side-channel attack mitigation, and firmware integrity verification for edge IoT gateways.', 'Cybersecurity, Embedded Systems', 'Edge Computing, Hardware Security, Trusted Execution Environment, IoT', 'Edge Security, Hardware Security, IoT, Firmware, Trusted Execution', 'University faculty and security research labs', 'Applied Research', 'Global', 'Research Grant', 'active')
ON DUPLICATE KEY UPDATE
title=VALUES(title), funder=VALUES(funder), amount_range=VALUES(amount_range), deadline=VALUES(deadline), semantic_fit=VALUES(semantic_fit), match_badges=VALUES(match_badges), description=VALUES(description), research_domains=VALUES(research_domains), technology_areas=VALUES(technology_areas), keywords=VALUES(keywords), eligibility=VALUES(eligibility), research_stage=VALUES(research_stage), geographic_scope=VALUES(geographic_scope), funding_type=VALUES(funding_type), status=VALUES(status);

INSERT INTO funding_opportunities (id, title, funder, amount_range, deadline, semantic_fit, match_badges, description, research_domains, technology_areas, keywords, eligibility, research_stage, geographic_scope, funding_type, status)
VALUES (16, 'Generative AI & Knowledge Graph Integration Seed Fund', 'Microsoft Research Outreach', '$70,000 - $150,000', '2026-12-20', 96, 'AI,LLM,Graph', 'Investigating the fusion of structured Knowledge Graphs with generative Large Language Models to improve reasoning accuracy and reduce hallucinations.', 'Artificial Intelligence, Knowledge Representation', 'Knowledge Graphs, LLMs, RAG, Generative AI, Graph Neural Networks', 'Knowledge Graphs, Generative AI, LLM, RAG, Graph Neural Networks, Semantic Web', 'Computer science faculty and AI doctoral labs', 'Basic Research', 'Global', 'Seed Funding', 'active')
ON DUPLICATE KEY UPDATE
title=VALUES(title), funder=VALUES(funder), amount_range=VALUES(amount_range), deadline=VALUES(deadline), semantic_fit=VALUES(semantic_fit), match_badges=VALUES(match_badges), description=VALUES(description), research_domains=VALUES(research_domains), technology_areas=VALUES(technology_areas), keywords=VALUES(keywords), eligibility=VALUES(eligibility), research_stage=VALUES(research_stage), geographic_scope=VALUES(geographic_scope), funding_type=VALUES(funding_type), status=VALUES(status);

INSERT INTO funding_opportunities (id, title, funder, amount_range, deadline, semantic_fit, match_badges, description, research_domains, technology_areas, keywords, eligibility, research_stage, geographic_scope, funding_type, status)
VALUES (17, 'Bio-Innovation & CRISPR Gene Editing Safety Accelerator', 'Bill & Melinda Gates Foundation', '$300,000 - $900,000', '2026-10-01', 80, 'BioTech', 'Precision CRISPR cas off-target monitoring, viral vector delivery optimization, and therapeutic safety evaluation for infectious disease intervention.', 'Biotechnology, Genomics', 'CRISPR Gene Editing, Genomic Sequencing, Vector Delivery', 'CRISPR, Biotechnology, Gene Editing, Genomics, Disease Therapy', 'Global biotechnology institutes and university bioengineering labs', 'Translational Research', 'Global', 'Accelerator', 'active')
ON DUPLICATE KEY UPDATE
title=VALUES(title), funder=VALUES(funder), amount_range=VALUES(amount_range), deadline=VALUES(deadline), semantic_fit=VALUES(semantic_fit), match_badges=VALUES(match_badges), description=VALUES(description), research_domains=VALUES(research_domains), technology_areas=VALUES(technology_areas), keywords=VALUES(keywords), eligibility=VALUES(eligibility), research_stage=VALUES(research_stage), geographic_scope=VALUES(geographic_scope), funding_type=VALUES(funding_type), status=VALUES(status);

INSERT INTO funding_opportunities (id, title, funder, amount_range, deadline, semantic_fit, match_badges, description, research_domains, technology_areas, keywords, eligibility, research_stage, geographic_scope, funding_type, status)
VALUES (18, 'Smart Cities & Intelligent Urban Transportation Systems', 'Department of Transportation (DOT)', '$100,000 - $350,000', '2026-09-25', 78, 'SmartCities', 'Traffic flow optimization using connected vehicle V2X communications, urban congestion predictive modeling, and micro-mobility integration.', 'Urban Planning, Data Science', 'Intelligent Transportation Systems, V2X, Traffic Analytics, IoT', 'Smart Cities, Transportation, V2X, Traffic Optimization, Urban Analytics', 'Municipal research consortia and civil engineering faculties', 'Development', 'United States', 'Research Grant', 'active')
ON DUPLICATE KEY UPDATE
title=VALUES(title), funder=VALUES(funder), amount_range=VALUES(amount_range), deadline=VALUES(deadline), semantic_fit=VALUES(semantic_fit), match_badges=VALUES(match_badges), description=VALUES(description), research_domains=VALUES(research_domains), technology_areas=VALUES(technology_areas), keywords=VALUES(keywords), eligibility=VALUES(eligibility), research_stage=VALUES(research_stage), geographic_scope=VALUES(geographic_scope), funding_type=VALUES(funding_type), status=VALUES(status);

INSERT INTO funding_opportunities (id, title, funder, amount_range, deadline, semantic_fit, match_badges, description, research_domains, technology_areas, keywords, eligibility, research_stage, geographic_scope, funding_type, status)
VALUES (19, 'Educational Technology & Adaptive Learning AI Grant', 'Department of Education Innovation Fund', '$40,000 - $120,000', '2026-11-20', 81, 'EdTech,AI', 'Personalized learning systems using adaptive pedagogical AI tutors, student engagement telemetry analysis, and automated rubric scoring tools.', 'Educational Technology, Artificial Intelligence', 'Adaptive Learning, AI Tutoring, Learning Analytics, NLP', 'EdTech, Adaptive Learning, AI Tutor, Automated Assessment, Learning Analytics', 'Educational researchers and K-12 innovation centers', 'Applied Research', 'United States', 'Research Grant', 'active')
ON DUPLICATE KEY UPDATE
title=VALUES(title), funder=VALUES(funder), amount_range=VALUES(amount_range), deadline=VALUES(deadline), semantic_fit=VALUES(semantic_fit), match_badges=VALUES(match_badges), description=VALUES(description), research_domains=VALUES(research_domains), technology_areas=VALUES(technology_areas), keywords=VALUES(keywords), eligibility=VALUES(eligibility), research_stage=VALUES(research_stage), geographic_scope=VALUES(geographic_scope), funding_type=VALUES(funding_type), status=VALUES(status);

INSERT INTO funding_opportunities (id, title, funder, amount_range, deadline, semantic_fit, match_badges, description, research_domains, technology_areas, keywords, eligibility, research_stage, geographic_scope, funding_type, status)
VALUES (20, 'Patent Commercialization & University Technology Transfer', 'National Innovation & Technology Transfer Board', '$50,000 - $150,000', '2026-10-31', 83, 'Patents,Innovation', 'Proof-of-concept validation, prototype maturation, and commercial licensing readiness for high-impact patented inventions in academic labs.', 'Technology Transfer, Innovation Management', 'Prototyping, Patent Licensing, Commercialization Strategy', 'Technology Transfer, Patents, Commercialization, Proof of Concept, Licensing', 'University IP holders and spin-off technology founders', 'Commercialization', 'Global', 'Innovation Grant', 'active')
ON DUPLICATE KEY UPDATE
title=VALUES(title), funder=VALUES(funder), amount_range=VALUES(amount_range), deadline=VALUES(deadline), semantic_fit=VALUES(semantic_fit), match_badges=VALUES(match_badges), description=VALUES(description), research_domains=VALUES(research_domains), technology_areas=VALUES(technology_areas), keywords=VALUES(keywords), eligibility=VALUES(eligibility), research_stage=VALUES(research_stage), geographic_scope=VALUES(geographic_scope), funding_type=VALUES(funding_type), status=VALUES(status);

INSERT INTO funding_opportunities (id, title, funder, amount_range, deadline, semantic_fit, match_badges, description, research_domains, technology_areas, keywords, eligibility, research_stage, geographic_scope, funding_type, status)
VALUES (21, 'Deep Learning for Protein Folding & Drug Discovery', 'Wellcome Trust', '$350,000 - $850,000', '2026-12-05', 92, 'Bio,DL', 'Machine learning computational frameworks predicting 3D macromolecular structures, ligand binding affinities, and target molecule synthesis routes.', 'Computational Biology, Machine Learning', 'Molecular Modeling, Deep Learning, Protein Folding, AlphaFold', 'Protein Folding, Drug Discovery, Computational Biology, Deep Learning, Molecular Structure', 'Postdoctoral researchers and structural biology groups', 'Basic Research', 'Global', 'Research Grant', 'active')
ON DUPLICATE KEY UPDATE
title=VALUES(title), funder=VALUES(funder), amount_range=VALUES(amount_range), deadline=VALUES(deadline), semantic_fit=VALUES(semantic_fit), match_badges=VALUES(match_badges), description=VALUES(description), research_domains=VALUES(research_domains), technology_areas=VALUES(technology_areas), keywords=VALUES(keywords), eligibility=VALUES(eligibility), research_stage=VALUES(research_stage), geographic_scope=VALUES(geographic_scope), funding_type=VALUES(funding_type), status=VALUES(status);

INSERT INTO funding_opportunities (id, title, funder, amount_range, deadline, semantic_fit, match_badges, description, research_domains, technology_areas, keywords, eligibility, research_stage, geographic_scope, funding_type, status)
VALUES (22, 'Renewable Offshore Wind Energy Hydrodynamics', 'Ocean Energy Agency', '$200,000 - $550,000', '2025-06-30', 70, 'Energy', 'Numerical modeling of floating offshore wind turbine moorings, wave interaction fatigue analysis, and seabed cable degradation.', 'Marine Engineering, Renewable Energy', 'Offshore Wind, Fluid Dynamics, Marine Turbines', 'Offshore Wind, Renewable Energy, Hydrodynamics, Marine Engineering, Turbines', 'Marine engineering institutes', 'Applied Research', 'Global', 'Research Grant', 'closed')
ON DUPLICATE KEY UPDATE
title=VALUES(title), funder=VALUES(funder), amount_range=VALUES(amount_range), deadline=VALUES(deadline), semantic_fit=VALUES(semantic_fit), match_badges=VALUES(match_badges), description=VALUES(description), research_domains=VALUES(research_domains), technology_areas=VALUES(technology_areas), keywords=VALUES(keywords), eligibility=VALUES(eligibility), research_stage=VALUES(research_stage), geographic_scope=VALUES(geographic_scope), funding_type=VALUES(funding_type), status=VALUES(status);

INSERT INTO funding_opportunities (id, title, funder, amount_range, deadline, semantic_fit, match_badges, description, research_domains, technology_areas, keywords, eligibility, research_stage, geographic_scope, funding_type, status)
VALUES (23, 'Marine Biology & Coral Reef Conservation Sensing', 'National Oceanic and Atmospheric Administration (NOAA)', '$45,000 - $110,000', '2026-11-10', 72, 'MarineBio', 'Autonomous underwater vehicle micro-sensor payloads measuring coral acidification, thermal stress indicators, and marine biodiversity soundscapes.', 'Marine Biology, Environmental Science', 'Underwater Autonomous Sensors, Acoustic Monitoring, eDNA', 'Marine Biology, Oceanography, Coral Reefs, Conservation, Underwater Sensors', 'Marine biology researchers and conservation foundations', 'Applied Research', 'Global', 'Research Grant', 'active')
ON DUPLICATE KEY UPDATE
title=VALUES(title), funder=VALUES(funder), amount_range=VALUES(amount_range), deadline=VALUES(deadline), semantic_fit=VALUES(semantic_fit), match_badges=VALUES(match_badges), description=VALUES(description), research_domains=VALUES(research_domains), technology_areas=VALUES(technology_areas), keywords=VALUES(keywords), eligibility=VALUES(eligibility), research_stage=VALUES(research_stage), geographic_scope=VALUES(geographic_scope), funding_type=VALUES(funding_type), status=VALUES(status);

INSERT INTO funding_opportunities (id, title, funder, amount_range, deadline, semantic_fit, match_badges, description, research_domains, technology_areas, keywords, eligibility, research_stage, geographic_scope, funding_type, status)
VALUES (24, 'Next-Gen Semiconductor Fabrication & Lithography', 'Semiconductor Research Corporation (SRC)', '$250,000 - $700,000', '2026-12-10', 89, 'Hardware,Semiconductors', 'Sub-2nm extreme ultraviolet (EUV) lithography resist chemistry, gate-all-around transistor defect inspection, and interconnect RC delay reduction.', 'Semiconductor Engineering, Physics', 'EUV Lithography, GAA Transistors, Sub-2nm Lithography', 'Semiconductors, Lithography, Microchips, GAAFET, EUV, Silicon Fabrication', 'Microelectronics research departments', 'Experimental Development', 'Global', 'Research Grant', 'active')
ON DUPLICATE KEY UPDATE
title=VALUES(title), funder=VALUES(funder), amount_range=VALUES(amount_range), deadline=VALUES(deadline), semantic_fit=VALUES(semantic_fit), match_badges=VALUES(match_badges), description=VALUES(description), research_domains=VALUES(research_domains), technology_areas=VALUES(technology_areas), keywords=VALUES(keywords), eligibility=VALUES(eligibility), research_stage=VALUES(research_stage), geographic_scope=VALUES(geographic_scope), funding_type=VALUES(funding_type), status=VALUES(status);

INSERT INTO funding_opportunities (id, title, funder, amount_range, deadline, semantic_fit, match_badges, description, research_domains, technology_areas, keywords, eligibility, research_stage, geographic_scope, funding_type, status)
VALUES (25, 'Privacy-Preserving Federated Learning in Finance', 'FinTech Innovation Council', '$85,000 - $220,000', '2026-10-20', 90, 'FinTech,ML', 'Distributed federated machine learning models using homomorphic encryption and differential privacy for multi-bank anti-money laundering detection.', 'Data Science, Cybersecurity, Financial Tech', 'Federated Learning, Differential Privacy, Homomorphic Encryption, Machine Learning', 'Federated Learning, Differential Privacy, FinTech, Encryption, Fraud Detection', 'Financial computing labs and computer science researchers', 'Applied Research', 'Global', 'Innovation Grant', 'active')
ON DUPLICATE KEY UPDATE
title=VALUES(title), funder=VALUES(funder), amount_range=VALUES(amount_range), deadline=VALUES(deadline), semantic_fit=VALUES(semantic_fit), match_badges=VALUES(match_badges), description=VALUES(description), research_domains=VALUES(research_domains), technology_areas=VALUES(technology_areas), keywords=VALUES(keywords), eligibility=VALUES(eligibility), research_stage=VALUES(research_stage), geographic_scope=VALUES(geographic_scope), funding_type=VALUES(funding_type), status=VALUES(status);

INSERT INTO funding_opportunities (id, title, funder, amount_range, deadline, semantic_fit, match_badges, description, research_domains, technology_areas, keywords, eligibility, research_stage, geographic_scope, funding_type, status)
VALUES (26, 'Explainable AI (XAI) for High-Stakes Decision Making', 'Defense Advanced Research Projects Agency (DARPA)', '$200,000 - $600,000', '2026-11-25', 94, 'XAI,AI', 'Human-understandable model attribution methods, counterfactual explanations, and trustworthy AI verification frameworks for critical systems.', 'Artificial Intelligence, Human-Computer Interaction', 'Explainable AI, Model Attribution, Counterfactual Reasoning, Interpretability', 'Explainable AI, XAI, Trustworthy AI, Interpretability, Decision Support, Model Attribution', 'AI ethics and machine learning research groups', 'Basic Research', 'United States', 'Contract', 'active')
ON DUPLICATE KEY UPDATE
title=VALUES(title), funder=VALUES(funder), amount_range=VALUES(amount_range), deadline=VALUES(deadline), semantic_fit=VALUES(semantic_fit), match_badges=VALUES(match_badges), description=VALUES(description), research_domains=VALUES(research_domains), technology_areas=VALUES(technology_areas), keywords=VALUES(keywords), eligibility=VALUES(eligibility), research_stage=VALUES(research_stage), geographic_scope=VALUES(geographic_scope), funding_type=VALUES(funding_type), status=VALUES(status);

INSERT INTO funding_opportunities (id, title, funder, amount_range, deadline, semantic_fit, match_badges, description, research_domains, technology_areas, keywords, eligibility, research_stage, geographic_scope, funding_type, status)
VALUES (27, 'Space Weather Forecasting & Magnetosphere Data Fusion', 'European Space Agency (ESA)', '$180,000 - $480,000', '2026-12-28', 79, 'Space,Astrophysics', 'Real-time solar flare trajectory modeling, coronal mass ejection shockwave prediction, and satellite radiation hazard warning systems.', 'Astrophysics, Data Science', 'Solar Magnetometry, Space Weather Analytics, Predictive Modeling', 'Space Weather, Solar Flares, ESA, Magnetosphere, Astrophysics, Radiation Protection', 'Astrophysics research institutes and space science laboratories', 'Applied Research', 'European Union', 'Research Grant', 'active')
ON DUPLICATE KEY UPDATE
title=VALUES(title), funder=VALUES(funder), amount_range=VALUES(amount_range), deadline=VALUES(deadline), semantic_fit=VALUES(semantic_fit), match_badges=VALUES(match_badges), description=VALUES(description), research_domains=VALUES(research_domains), technology_areas=VALUES(technology_areas), keywords=VALUES(keywords), eligibility=VALUES(eligibility), research_stage=VALUES(research_stage), geographic_scope=VALUES(geographic_scope), funding_type=VALUES(funding_type), status=VALUES(status);

INSERT INTO funding_opportunities (id, title, funder, amount_range, deadline, semantic_fit, match_badges, description, research_domains, technology_areas, keywords, eligibility, research_stage, geographic_scope, funding_type, status)
VALUES (28, 'India National AI for Agriculture & Water Security', 'NITI Aayog Innovation Mission (India)', '₹2,500,000 - ₹7,500,000 ($30,000 - $90,000)', '2026-10-10', 88, 'India,AgTech,AI', 'AI-driven monsoon rainfall forecasting, ground-water table extraction monitoring, and regional crop yield risk insurance assessment across Indian agricultural belts.', 'Smart Agriculture, Artificial Intelligence, Water Resources', 'Computer Vision, Remote Sensing, AI Weather Prediction, GIS', 'Agriculture, India, Monsoon Forecasting, Water Security, Crop Insurance, AI', 'Indian academic institutions, ICAR labs, and approved AgTech incubators', 'Applied Research', 'India', 'Seed Funding', 'active')
ON DUPLICATE KEY UPDATE
title=VALUES(title), funder=VALUES(funder), amount_range=VALUES(amount_range), deadline=VALUES(deadline), semantic_fit=VALUES(semantic_fit), match_badges=VALUES(match_badges), description=VALUES(description), research_domains=VALUES(research_domains), technology_areas=VALUES(technology_areas), keywords=VALUES(keywords), eligibility=VALUES(eligibility), research_stage=VALUES(research_stage), geographic_scope=VALUES(geographic_scope), funding_type=VALUES(funding_type), status=VALUES(status);

INSERT INTO funding_opportunities (id, title, funder, amount_range, deadline, semantic_fit, match_badges, description, research_domains, technology_areas, keywords, eligibility, research_stage, geographic_scope, funding_type, status)
VALUES (29, 'Swarm Robotics for Search & Rescue in Disaster Zones', 'Red Cross Humanitarian Technology Fund', '$50,000 - $160,000', '2026-09-05', 87, 'Robotics,Humanitarian', 'Distributed multi-robot coordination algorithms, mesh communication networks, and thermal victim detection for urban search and rescue operations.', 'Robotics, Autonomous Systems', 'Swarm Robotics, Mesh Networking, Thermal Sensing, Multi-Agent Systems', 'Swarm Robotics, Search and Rescue, Disaster Relief, Multi-Agent Systems, Autonomous Swarms', 'Robotics research laboratories and disaster response tech groups', 'Prototyping', 'Global', 'Challenge Grant', 'active')
ON DUPLICATE KEY UPDATE
title=VALUES(title), funder=VALUES(funder), amount_range=VALUES(amount_range), deadline=VALUES(deadline), semantic_fit=VALUES(semantic_fit), match_badges=VALUES(match_badges), description=VALUES(description), research_domains=VALUES(research_domains), technology_areas=VALUES(technology_areas), keywords=VALUES(keywords), eligibility=VALUES(eligibility), research_stage=VALUES(research_stage), geographic_scope=VALUES(geographic_scope), funding_type=VALUES(funding_type), status=VALUES(status);

INSERT INTO funding_opportunities (id, title, funder, amount_range, deadline, semantic_fit, match_badges, description, research_domains, technology_areas, keywords, eligibility, research_stage, geographic_scope, funding_type, status)
VALUES (30, 'Circular Economy & Plastic Recycling Catalyst Chemistry', 'Global Environmental Facility (GEF)', '$120,000 - $380,000', '2026-11-05', 76, 'Chemistry,Environment', 'Enzymatic plastic depolymerization, catalytic chemical recycling of mixed post-consumer polymers, and closed-loop material lifecycle design.', 'Chemistry, Environmental Science', 'Enzymatic Recycling, Catalysts, Polymer Chemistry, Circular Economy', 'Plastic Recycling, Circular Economy, Polymer Chemistry, Catalysis, Waste Reduction', 'University chemistry departments and environmental research institutes', 'Experimental Development', 'Global', 'Innovation Grant', 'active')
ON DUPLICATE KEY UPDATE
title=VALUES(title), funder=VALUES(funder), amount_range=VALUES(amount_range), deadline=VALUES(deadline), semantic_fit=VALUES(semantic_fit), match_badges=VALUES(match_badges), description=VALUES(description), research_domains=VALUES(research_domains), technology_areas=VALUES(technology_areas), keywords=VALUES(keywords), eligibility=VALUES(eligibility), research_stage=VALUES(research_stage), geographic_scope=VALUES(geographic_scope), funding_type=VALUES(funding_type), status=VALUES(status);
